keep-open=yes
gpu-api=opengl
# osd-level=3

# [something]
# profile-desc=HD video sucks
# profile-cond=width >= 1280
# hue=-50

[something]
profile-desc=Show osd when no video
profile-cond=not p['video']
osc=no
osd-level=3
