[colors.bright]
black = "#000000"
blue = "#00ff00"
cyan = "#00ff00"
green = "#00ff00"
magenta = "#00ff00"
red = "#00ff00"
white = "#00ff00"
yellow = "#00ff00"

[colors.normal]
black = "#000000"
blue = "#00ff00"
cyan = "#00ff00"
green = "#00ff00"
magenta = "#00ff00"
red = "#00ff00"
white = "#00ff00"
yellow = "#00ff00"

[colors.primary]
background = "#000000"
foreground = "#00ff00"

