#!/usr/bin/env bash
# (generated by Matugen)
# apply some settings to GTK

dconf write /org/gnome/desktop/interface/gtk-theme "'adw-gtk3'"
dconf write /org/gnome/desktop/interface/color-scheme "'prefer-{{mode | to_lower}}'"
dconf write /org/gnome/desktop/interface/icon-theme "'Papirus-{{mode | to_upper}}'"

